# Generated by Django 6.0.6 on 2026-06-21 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, help_text='Preenchido ao marcar como Pago no painel. Deixe em branco para destaque sem prazo definido.', null=True, verbose_name='Destaque válido até'),
        ),
        migrations.AddField(
            model_name='listing',
            name='instagram',
            field=models.URLField(blank=True, help_text='Link completo do perfil. Só aparece publicado se o plano for Pago.', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='listing',
            name='website',
            field=models.URLField(blank=True, help_text='Link do site/cardápio digital. Só aparece publicado se o plano for Pago.', verbose_name='Site'),
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='anuncios/galeria/')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Foto da galeria',
                'verbose_name_plural': 'Fotos da galeria',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
