# Generated by Django 6.0.6 on 2026-06-23 16:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_data_expiracao_listing_instagram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(help_text='Numero de estrelas (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(blank=True, help_text='Comentario opcional (ate 200 caracteres)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(help_text='Anuncio sendo avaliado', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='listings.listing')),
                ('user', models.ForeignKey(help_text='Usuario que fez a avaliacao', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliacao',
                'verbose_name_plural': 'Avaliacoes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', '-created_at'], name='listings_ra_listing_853529_idx'), models.Index(fields=['user', '-created_at'], name='listings_ra_user_id_890652_idx')],
                'unique_together': {('listing', 'user')},
            },
        ),
    ]
