# Generated by Django 6.0.6 on 2026-06-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título do Banner')),
                ('imagem', models.ImageField(upload_to='banners/', verbose_name='Imagem do Banner')),
                ('link_destino', models.URLField(blank=True, help_text='Link para onde o usuário será enviado ao clicar', null=True, verbose_name='Link de Destino (Opcional)')),
                ('ativo', models.BooleanField(default=True, help_text='Marque para exibir no topo do site', verbose_name='Ativo?')),
                ('ordem', models.IntegerField(default=0, help_text='Números menores aparecem primeiro', verbose_name='Ordem de Exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner Rotativo',
                'verbose_name_plural': 'Banners Rotativos',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
