# Generated by Django 6.0.6 on 2026-06-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='destaque_topo',
            field=models.BooleanField(default=False, help_text='Se marcado, o logotipo aparecerá no banner rotativo do topo (apenas enquanto o plano pago estiver válido).', verbose_name='Exibir no Carrossel do Topo?'),
        ),
    ]
