# Generated by Django 6.0.6 on 2026-06-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listingimage_destaque_topo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='destaque_topo',
        ),
        migrations.AddField(
            model_name='listing',
            name='destaque_topo',
            field=models.BooleanField(default=False, help_text='Se marcado, o logotipo aparecerá no banner rotativo do topo (apenas enquanto o plano pago estiver válido).', verbose_name='Exibir no Carrossel do Topo?'),
        ),
    ]
