# Generated by Django 6.0.6 on 2026-06-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listingimage_destaque_topo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='data_expiracao_topo',
            field=models.DateTimeField(blank=True, help_text='Deixe em branco para tempo ilimitado ou defina a data limite para o banner sumir do topo.', null=True, verbose_name='Vencimento do Banner do Topo'),
        ),
    ]
