# Generated by Django 6.0.6 on 2026-07-01 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_data_expiracao_topo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anunciante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('is_whatsapp', models.BooleanField(default=False, verbose_name='É WhatsApp?')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física (CPF)'), ('PJ', 'Pessoa Jurídica (CNPJ)')], default='PF', max_length=2)),
                ('documento', models.CharField(max_length=18, unique=True)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('email_confirmado', models.BooleanField(default=False)),
                ('token_ativacao', models.CharField(blank=True, max_length=64, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anunciantes', to='listings.cidade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anunciante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
